// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/process-section/Journey.tsx": () => import("../components/mockups/process-section/Journey.tsx"),
  "./components/mockups/process-section/Orbital.tsx": () => import("../components/mockups/process-section/Orbital.tsx"),
  "./components/mockups/process-section/Pipeline.tsx": () => import("../components/mockups/process-section/Pipeline.tsx"),
  "./components/mockups/process-section/Stepper.tsx": () => import("../components/mockups/process-section/Stepper.tsx")
};
